language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"

before_install:
  - npm install -g bower
  - npm install -g gulp

install:
  - npm install
  - bower install

before_script:
  - gulp default
